export const SELECT_COUNTRY = 'SELECT_COUNTRY'

export const FETCH_GEO_REQUEST = 'FETCH_GEO_REQUEST'
export const FETCH_GEO_SUCCESS = 'FETCH_GEO_SUCCESS'
export const FETCH_GEO_FAILURE = 'FETCH_GEO_FAILURE'

export const FETCH_OFFICES_REQUEST = 'FETCH_OFFICES_REQUEST'
export const FETCH_OFFICES_SUCCESS = 'FETCH_OFFICES_SUCCESS'
export const FETCH_OFFICES_FAILURE = 'FETCH_OFFICES_FAILURE'

export const FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST'
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS'
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE'
